[package]
name = "dumac"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.174"
parking_lot = "0.12.4"
rayon = "1.10.0"


[dev-dependencies]
tempfile = "3.8"

[profile.release]
debug = true
